Repository atom-community/terminal, pull requests merged in 2021-07, with the labels that each got.

#81 fix: add padding to the terminal
  styles/terminal.less
Labels: bug

#80 fix: add terminal syntax variables to standard theme
  README.md
  spec/themes-spec.js
  src/config.ts
  src/element.ts
  src/model.ts
  src/terminal.ts
  src/themes.ts
  styles/terminal.less
Labels: enhancement

#86 Reduce the size of the bundle
  .github/workflows/CI.yml
  .gitignore
  .terserrc.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Dependencies
